
languageCode = "en-us"
baseURL = "https://tayphormade.github.io/"
title = "TayphorMade Recipes"

theme = "gochowdown"

[params]
    description = "A description for the meta tag of the site"
    googleSearch = "tayphormade"
    showDate = false # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page

    tagsInHome = 40     # set zero to not show in home page
    sectionsInHome = 5  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 5

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "All Tags"
        url = "/tags/"
        weight = 1
    [[menu.main]]
        name = "Author"
        url = "/author/"
        weight = 1

# vim: et

